# Generated by Django 4.2.30 on 2026-07-07 05:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food category (e.g., Pizza, Burgers, Drinks)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the category')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the category was last updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the menu item (e.g., Margherita Pizza)', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the item (must be greater than zero)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_available', models.BooleanField(default=True, help_text='Whether this item is currently available for ordering')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the menu item')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the item was last updated')),
                ('category', models.ForeignKey(help_text='Category this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.category')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Display name of the customer', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items ordered (must be greater than zero)', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the order', max_length=20)),
                ('delivery_address', models.TextField(blank=True, default='', help_text='Delivery address for this order')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Geocoded latitude of delivery address (Google Maps API)', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Geocoded longitude of delivery address (Google Maps API)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was placed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the order was last updated')),
                ('customer', models.ForeignKey(help_text='The user who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='The menu item that was ordered', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.menuitem')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
