# Generated by Django 6.0.4 on 2026-05-06 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bus_type', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('total_ratings', models.CharField(default='0 ratings', max_length=50)),
                ('amenities', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('badge', models.CharField(default='Limited time', max_length=50)),
                ('color_class', models.CharField(default='offer-1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('stops', models.CharField(default='Non-stop', max_length=50)),
                ('price', models.IntegerField()),
                ('seats_available', models.IntegerField(default=30)),
                ('bus_type_tags', models.CharField(default='ac sleeper', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='booking.city')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.busoperator')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='booking.city')),
            ],
        ),
        migrations.CreateModel(
            name='DroppingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropping_points', to='booking.route')),
            ],
        ),
        migrations.CreateModel(
            name='BoardingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_points', to='booking.route')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('deck', models.CharField(choices=[('lower', 'Lower'), ('upper', 'Upper')], default='lower', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('female', 'Female Booked')], default='available', max_length=20)),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('window', 'Window'), ('upper', 'Upper Deck'), ('premium', 'Premium Upper')], default='standard', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.route')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('route', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_email', models.CharField(max_length=200)),
                ('passenger_phone', models.CharField(max_length=20)),
                ('total_amount', models.IntegerField(default=0)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('boarding_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.boardingpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('dropping_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.droppingpoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.route')),
                ('seats', models.ManyToManyField(to='booking.seat')),
            ],
        ),
    ]
