# Generated by Django 6.0.4 on 2026-06-19 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('price_per_hour', models.IntegerField()),
                ('price_per_day', models.IntegerField()),
                ('seats', models.IntegerField(choices=[(4, '4'), (5, '5'), (7, '7'), (9, '9')])),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_airbags', models.BooleanField(default=False)),
                ('has_abs', models.BooleanField(default=False)),
                ('has_gps', models.BooleanField(default=False)),
                ('has_music_system', models.BooleanField(default=False)),
                ('has_reverse_camera', models.BooleanField(default=False)),
                ('airbags_count', models.IntegerField(default=0)),
                ('tyre_condition', models.CharField(max_length=50)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('agency', models.ForeignKey(limit_choices_to={'usertype': 'agency'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
